### PR TITLE
[wip] mesh loading example

### PR DESCRIPTION
**Pull request by sjkelly**
I noticed the `geometry` function was added and I was curious if it could be made to work with the `HomogenousMesh` type in GeometryTypes.
The conversion is not nearly generic enough to work on all supported geometries. This is WIP since I have the following questions: Would it make sense to provide some conversions from GeometryTypes in this package? The my naive attempt at eventing doesn't seem to work.

### CODE REVIEW

**Comment by rohitvarkey** [comment]
Sorry for the late reply!

This is really cool and what I wanted to accomplish when I saw your `ThreeJS` mesh too. :smile: This works nicely for me, except that the sliders don't seem to update the geometry (is that what you meant by eventing?). I will look into that soon. But being able to actually load .obj files and showing actual objects like that cat is really awesome!

I think having conversions from GeomertyTypes would be useful with respect to the whole Julia graphics ecosystem and getting everything to work nicely together.

**Comment by sjkelly** [comment]
Thanks! You are right, by "eventing" I mean updating the geometry. It is good to hear we could bring some GeometryTypes definitions in here. In the meantime I will work on that until the update issues get sorted out.

**Comment by rohitvarkey** [comment]
@sjkelly I've got "eventing" working for `geometry` now. :smile:  #14 has fixed the update problems. 
Your example works fine for me now.

scale_cat

Would you mind getting rid of the other commits except for e2198906c5f80f415b029e47304478f2ff539887? That fix didn't work anyway. :)

Thanks again!

**Comment by sjkelly** [comment]
Sweet! I rebased this and moved the AbstractMesh->geometry function into the package. This now adds a dependency on GeometryTypes.

**Comment by rohitvarkey** [comment]
Thanks again! :smile:

**Pull request merged**
